INSERT INTO STORE (ID, NAME, PHONE_NUM, OPEN_TIME, CLOSED_TIME) VALUES(1, '집게리아', '010-1234-5678', 9, 18);
INSERT INTO MENU (ID, NAME, MENU_TYPE, DISCOUNT_POLICY, PRICE, DISCRIPTION) VALUES(1, '콜라', '${MenuType.SIDE.toString()}', '${DiscountPolicy.DEFAULT.toString()', 1000, '코카콜라');
INSERT INTO MENU (ID, NAME, MENU_TYPE, DISCOUNT_POLICY, PRICE, DISCRIPTION) VALUES(2, '감자튀김', 'SIDE', 'DEFAULT', 500, '프렌치프라이');






-- INSERT INTO MENU (ID, NAME, MENU_TYPE, DISCOUNT_POLICY, PRICE, DESCRIPTION) VALUES(1, '콜라', 'SIDE', 'DEFAULT', 1000, '코카콜라');